### ISSUE TITLE
Parameter 1 of constructor in org.openwms.core.uaa.auth.impl.ClientServiceImpl required a bean of type 'org.openwms.core.uaa.auth.ClientMapper' that could not be found.

### ISSUE THREAD

**Issue by dnsh87** [openwms/org.openwms.core.uaa#15]
***************************
APPLICATION FAILED TO START
***************************
Description:

Parameter 1 of constructor in org.openwms.core.uaa.auth.impl.ClientServiceImpl required a bean of type 'org.openwms.core.uaa.auth.ClientMapper' that could not be found.

Action:

Consider defining a bean of type 'org.openwms.core.uaa.auth.ClientMapper' in your configuration.

**Comment by openwms** [comment]
How do you run the application to get this error? The bean implementation is generated at compile time and is a MapStruct mapper. When the application is built with Maven the code is generated. If you run the application within an IDE you should consider building it before with Maven or install a MapStruct plugin in the IDE

**Comment by dnsh87** [comment]
While running using cmd command "**mvnw package**", I am getting below exception
![maven_error](https://user-images.githubusercontent.com/9465348/114130501-550e4800-991e-11eb-8623-e6b9a286665d.png)

and While running in IDE I am getting below message :

Description:

Parameter 1 of constructor in org.openwms.core.uaa.auth.impl.ClientServiceImpl required a bean of type 'org.openwms.core.uaa.auth.ClientMapper' that could not be found.

Action:

Consider defining a bean of type 'org.openwms.core.uaa.auth.ClientMapper' in your configuration.

**Comment by openwms** [comment]
Java 11 is a minimum requirement to built most of the services. What do you get with `javac -version` ? Could you try to skip the enforcer with `mvnw package -Denforcer.skip=true` ? What IDE are you using?

**Comment by dnsh87** [comment]
I am using ### Java version 11.0.10 2021-01-19 LTS, you can check it in above image.
and  I am using **Eclipse** IDE [Version: 2020-03 (4.15.0)].

Still getting error with **mvnw package -Denforcer.skip=true**

**F:\Office\workspace_2021\org.openwms.core.uaa-master>mvnw package -Denforcer.skip=true
[INFO] Scanning for projects...
[WARNING] The POM for commons-net:commons-net:jar:3.6 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for commons-io:commons-io:jar:2.6 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO]
[INFO] ------------------< org.openwms:org.openwms.core.uaa >------------------
[INFO] Building OpenWMS.org CORE: UAA 1.1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ org.openwms.core.uaa ---
[INFO] Skipping Rule Enforcement.
[INFO]
[INFO] --- spring-boot-maven-plugin:2.3.7.RELEASE:build-info (repackage) @ org.openwms.core.uaa ---
[WARNING] The POM for commons-codec:commons-codec:jar:1.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ org.openwms.core.uaa ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 10 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ org.openwms.core.uaa ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 63 source files to F:\Office\workspace_2021\org.openwms.core.uaa-master\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] javac: invalid flag: --release
Usage: javac <options> <source files>
use -help for a list of possible options

[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.281 s
[INFO] Finished at: 2021-04-09T13:16:59+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project org.openwms.core.uaa: Compilation failure
[ERROR] javac: invalid flag: --release
[ERROR] Usage: javac <options> <source files>
[ERROR] use -help for a list of possible options
[ERROR]
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException**

**Comment by openwms** [comment]
Seems here is something wrong with your Java installation. Where is `%JAVA_HOME%` pointing to?

**Comment by dnsh87** [comment]
I have changed my %JAVA_HOME%, That was my mistake, But Now when I am executing "**mvn -DskipTests=true  package**" cmd,
I am getting :
[WARNING]
Dependency convergence error for joda-time:joda-time:2.3 paths to dependency are:
+-org.openwms:org.openwms.core.uaa:1.1.0-SNAPSHOT
  +-org.springframework.cloud:spring-cloud-starter-netflix-eureka-client:2.2.6.RELEASE
    +-com.netflix.eureka:eureka-client:1.10.7
      +-com.netflix.netflix-commons:netflix-eventbus:0.3.0
        +-com.netflix.netflix-commons:netflix-infix:0.3.0
          +-joda-time:joda-time:2.3
and
+-org.openwms:org.openwms.core.uaa:1.1.0-SNAPSHOT
  +-org.springframework.cloud:spring-cloud-starter-netflix-eureka-client:2.2.6.RELEASE
    +-com.netflix.eureka:eureka-core:1.10.7
      +-com.amazonaws:aws-java-sdk-core:1.11.792
        +-joda-time:joda-time:2.8.1

[WARNING] Rule 2: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability the error(s) are [
Dependency convergence error for joda-time:joda-time:2.3 paths to dependency are:
+-org.openwms:org.openwms.core.uaa:1.1.0-SNAPSHOT
  +-org.springframework.cloud:spring-cloud-starter-netflix-eureka-client:2.2.6.RELEASE
    +-com.netflix.eureka:eureka-client:1.10.7
      +-com.netflix.netflix-commons:netflix-eventbus:0.3.0
        +-com.netflix.netflix-commons:netflix-infix:0.3.0
          +-joda-time:joda-time:2.3
and
+-org.openwms:org.openwms.core.uaa:1.1.0-SNAPSHOT
  +-org.springframework.cloud:spring-cloud-starter-netflix-eureka-client:2.2.6.RELEASE
    +-com.netflix.eureka:eureka-core:1.10.7
      +-com.amazonaws:aws-java-sdk-core:1.11.792
        +-joda-time:joda-time:2.8.1
]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34.958 s
[INFO] Finished at: 2021-04-12T09:21:56+05:30
[INFO] Final Memory: 36M/127M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.2:enforce (enforce-maven) on project org.openwms.core.uaa: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by openwms** [comment]
What branch are you building? Not sure about the maven version you use. Could you please try to run the delivered maven version with `mvnw clean install` ? This is also what the CI runner is calling to execute the build. CI succeeds without errors. No artifact cache is used on CI, so perhaps delete all artifacts under your `%M2_HOME%\repository\org\openwms`.
